name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    - name: Run tests
      run: yarn run coverage
    
    - name: "Upload coverage report"
      run: |
       ci_env=`curl -s https://codecov.io/env`
       npm install codecov -g
       codecov -t 5ffc613a-05ee-43c1-bc5d-1a84903f9cc8
